#!/bin/sh
## grub-mkconfig -o /boot/grub/grub.cfg
## Copyright (C) by Miles Bradley Huff from 2019-2021 per the LGPL3 (the Third Lesser GNU Public License)

## Features
## -----------------------------------------------------------------------------
## Preload both GPT and MBR modules so that they are not missed
GRUB_PRELOAD_MODULES='part_gpt part_msdos'
## Uncomment to enable support for dm-crypt
#GRUB_ENABLE_CRYPTODISK='y'

## Timeouts
## -----------------------------------------------------------------------------
GRUB_DEFAULT=0
GRUB_TIMEOUT=0
GRUB_HIDDEN_TIMEOUT=1
GRUB_HIDDEN_TIMEOUT_QUIET='false'
GRUB_RECORDFAIL_TIMEOUT=${GRUB_HIDDEN_TIMEOUT}

## Targets
## -----------------------------------------------------------------------------
GRUB_DISTRIBUTOR='Arch'
GRUB_DISABLE_RECOVERY='false'
#GRUB_DEFAULT='saved'
#GRUB_SAVEDEFAULT='true'

## Boot flags
## -----------------------------------------------------------------------------
## i915 options go in /etc/modprobe.d/i915.conf
_BIOS='iomem=relaxed'
_BUGS='net.ifnames=0'
_DISPLAY='vga=current'
_LOGGING='loglevel=4 rd.udev.log_priority=4 rd.systemd.show_status=auto'
_PRETTY='splash quiet vt.global_cursor_default=0'
_SECURITY='apparmor=1 security=apparmor'
_SYSTEM='resume=/swap'
_ZSWAP='zswap.enabled=1 zswap.compressor=zstd zswap.max_pool_percent=25'

## Used for all Linux boots, including recovery
GRUB_CMDLINE_LINUX="${_BIOS} ${_BUGS} ${_DISPLAY} ${_LOGGING} ${_SECURITY} ${_SYSTEM} ${_ZSWAP}"
## Used for all non-recovery Linux boots
GRUB_CMDLINE_LINUX_DEFAULT="${_PRETTY}"

## Graphics
## -----------------------------------------------------------------------------
GRUB_TERMINAL_INPUT='console,auto'
#GRUB_TERMINAL_OUTPUT='console'
GRUB_GFXMODE='1920x1080,1280x1024,auto'
GRUB_GFXPAYLOAD_LINUX='keep,text,auto'

## Appearance
## -----------------------------------------------------------------------------
#_THEMEPATH='/boot/grub/themes'
#GRUB_THEME="${_THEMEPATH}/gfxtheme"
#GRUB_BACKGROUND="${_THEMEPATH}/wallpaper"
GRUB_COLOR_NORMAL='white/black'
GRUB_COLOR_HIGHLIGHT='black/white'
#GRUB_INIT_TUNE='480 440 1'
